name: Bug report
description: Report incorrect behavior, crashes, parsing problems, or wrong totals/costs.
title: 'bug: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please include a minimal repro so we can debug quickly.

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues.
          required: true
        - label: I reproduced on the latest released version.
          required: true

  - type: textarea
    id: command
    attributes:
      label: Command used
      description: Exact command(s) that trigger the issue.
      placeholder: llm-usage monthly --source pi --json
      render: shell
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened? Include errors, wrong totals, missing rows, etc.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect instead?
    validations:
      required: true

  - type: dropdown
    id: sources
    attributes:
      label: Data source(s)
      multiple: true
      options:
        - pi
        - codex
        - gemini
        - opencode
        - unknown
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Paste output of `llm-usage --version`, `node --version`, and your OS.
      placeholder: |
        llm-usage: x.y.z
        node: v24.x
        os: Ubuntu 24.04
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Diagnostics / logs (optional)
      description: Paste relevant stderr output. Redact secrets/paths if needed.
      render: text

  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: Anything else that might help reproduce.
